import { createHash } from 'node:crypto'

/**
 * Minimal copy of the agent's access-code utilities (packages/agent/src/core/access-code.ts).
 * Duplicated intentionally: serverless functions must bundle within this project.
 * Keep in sync with the agent — the sha256 hashing MUST match exactly or
 * codes generated by `fourier link` won't resolve.
 */

const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ' // Crockford: no I, L, O, U

export function hashCode(rawCode: string): string {
  return createHash('sha256').update(rawCode.trim().toUpperCase()).digest('hex')
}

/** Normalize user input: uppercase, fix common confusions, keep dashes optional. */
export function normalizeCode(input: string): string {
  const cleaned = input
    .trim()
    .toUpperCase()
    .replace(/O/g, '0')
    .replace(/[IL]/g, '1')
    .replace(/[^0-9A-Z]/g, '')
  const body = cleaned.startsWith('FK') ? cleaned.slice(2) : cleaned
  const groups = body.match(/.{1,5}/g) ?? []
  return ['FK', ...groups.filter(g => g.length === 5)].join('-')
}

export const CODE_ALPHABET = ALPHABET
